# Generated by Django 6.0.3 on 2026-03-19 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_todos_options_todos_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todos',
            old_name='author',
            new_name='user',
        ),
    ]
