# Generated by Django 6.0.3 on 2026-03-24 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='modified_at',
            new_name='updated_at',
        ),
    ]
