services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: restar
      MYSQL_USER: mqsql_user
      MYSQL_PASSWORD: qwe1234r
      MYSQL_ROOT_PASSWORD: qwe1234r
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: .
    command: uv run python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
      - venv_data:/app/.venv
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy

volumes:
  mysql_data:
  venv_data:
